# Feed
copyRight: Copyright (c) 2020-2022 roc
alert: true
alertDismissable: true
# alertText: "Introducing the Doks child theme, several DX + UX updates, and more! <a class=\"alert-link stretched-link\" href=\"https://getdoks.org/blog/doks-v0.2/\" target=\"_blank\" rel=\"noopener\">Check out Doks v0.2</a>"
alertText: HTTP3 support is incoming!
  <a class="alert-link stretched-link"
  href="https://req.cool/blog/http3-support-is-coming/">Try it out in advance</a>
