alert: true
alertDismissable: true
# alertText: "Introducing the Doks child theme, several DX + UX updates, and more! <a class=\"alert-link stretched-link\" href=\"https://getdoks.org/blog/doks-v0.2/\" target=\"_blank\" rel=\"noopener\">Check out Doks v0.2</a>"
alertText: 即将支持 HTTP3!
  <a class="alert-link stretched-link"
  href="https://req.cool/zh/blog/%E5%8D%B3%E5%B0%86%E6%94%AF%E6%8C%81-http3/">快来提前尝鲜体验吧</a>
