alert: true
alertDismissable: true
# alertText: "Introducing the Doks child theme, several DX + UX updates, and more! <a class=\"alert-link stretched-link\" href=\"https://getdoks.org/blog/doks-v0.2/\" target=\"_blank\" rel=\"noopener\">Check out Doks v0.2</a>"
alertText: <a class="alert-link stretched-link" href="/zh/blog/http3-%E7%8E%B0%E5%B7%B2%E6%AD%A3%E5%BC%8F%E6%94%AF%E6%8C%81/">HTTP3 现已正式支持!</a>
